UI focus feature fixed
monetr/monetr pull request #1212
Opened 2022-11-11 11:00 UTC by shubhay09

2022-11-11 20:06 UTC, elliotcourant commented
Why close the original pull request?

2022-11-12 05:46 UTC, shubhay09 commented
i thought it was not going to work can you review the changes ??

2022-11-12 05:52 UTC, shubhay09 commented
i dont know why im getting deepsource javascript error can you help out ?

2022-11-14 13:20 UTC, shubhay09 reviewed
review required

2022-11-15 15:21 UTC, elliotcourant requested changes
Just some small tweaks then this should be good to go!

2022-11-15 15:21 UTC, elliotcourant commented on ui/components/Authentication/Registration/RegisterView.tsx
> +                              className="hover:text-blue-500 hover:underline focus:ring-2 focus:ring-blue-600"
```suggestion
                              className="hover:text-blue-500 hover:underline focus:ring-2 focus:ring-blue-500 focus:underline"
```

2022-11-15 15:21 UTC, elliotcourant commented on ui/components/Authentication/Registration/RegisterView.tsx
> +                             I agree to monetr's&nbsp;
```suggestion
                            I agree to monetr's&nbsp;
```

2022-11-15 15:21 UTC, elliotcourant commented on ui/components/Authentication/Registration/RegisterView.tsx
> +                              className="hover:text-blue-500 hover:underline focus:ring-2 focus:ring-blue-600"
```suggestion
                              className="hover:text-blue-500 hover:underline focus:ring-2 focus:ring-blue-500 focus:underline"
```

2022-11-15 15:21 UTC, elliotcourant commented on ui/components/Authentication/Registration/RegisterView.tsx
> +                         }
```suggestion
                        }
```

2022-11-16 19:30 UTC, shubhay09 commented
changes have been made

2022-11-16 19:34 UTC, shubhay09 reviewed
changes have been you can review now and let me know anything else to be done or changed

2022-11-16 20:13 UTC, merged